# Generated by Django 3.2.19 on 2023-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
