# Generated by Django 3.2.19 on 2023-07-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substance',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
