# Generated by Django 3.2.19 on 2023-07-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_substance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='shopComment',
        ),
    ]
